### 1. Setup & Import

In [ ]:
#pandas used as data manipulation 
#numpy used to deal data with numerical value 
#data structure used in series and dataframe in pandas

In [5]:
pip install pandas

Requirement already satisfied: pandas in c:\users\saksh\appdata\local\programs\python\python312\lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in c:\users\saksh\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\saksh\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\saksh\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in c:\users\saksh\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.2.2
[notice] To update, run: C:\Users\saksh\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

In [6]:
import pandas as pd
import numpy as np

In [7]:
pd.__version__

'3.0.6'

### 2. Creating DataFrames and Series

##### pd.Series() - create a 1D labeled array

In [10]:
s=pd.Series([10,20,30])
s

0    10
1    20
2    30
dtype: int64

In [11]:
s=pd.Series([10,20,30],index=['a','b','c'],name='values')
s

a    10
b    20
c    30
Name: values, dtype: int64

##### pd.DataFrame() - from a dict of lists - create a labeled 2D table

In [12]:
df = pd.DataFrame({
    'name': ['Alice','Bob','Charlie','David'],
    'age':[25,30,35,40],
    'city':['NY','LA','SF','Goa']
})
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40  Goa

##### pd.DataFrame() - from a list of dicts

In [13]:
pd.DataFrame([{'a':1,'b':2},{'a':2,'b':4}])

   a  b
0  1  2
1  2  4

##### pd.DataFrame() - from a NumPy array

In [ ]:
pd.DataFrame(np.arange(6).reshape(2,3),columns=['x','y','z'])           #reshape in 2 rows and 3 col with col name x y and z and array value startwith 0 to 5

### 3. Attributes & Inspection

.shape = (rows,columns)

In [17]:
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40  Goa

In [18]:
df.shape

(4, 3)

.columns - columns labels

In [19]:
df.columns

Index(['name', 'age', 'city'], dtype='str')

.index - row labels

In [20]:
df.index

RangeIndex(start=0, stop=4, step=1)